### Hello world
GET http://localhost:5000/
Accept: application/json

### Get all todos
GET http://localhost:5000/todos/
Accept: application/json

### Get a single todo
GET http://localhost:5000/todos/3
Accept: application/json

### Get todo count
GET http://localhost:5000/todos/count
Accept: application/json

### Add a todo
POST http://localhost:5000/todos/add
Content-Type: application/json

{
  "title": "New todo #1"
}
