### Hello world
GET http://localhost:5000/
Accept: application/json

### Get all todos
GET http://localhost:5000/todos/
Accept: application/json

### Get a single todo
GET http://localhost:5000/todos/1
Accept: application/json

### Get todo count
GET http://localhost:5000/todos/count
Accept: application/json

### Add a todo
POST http://localhost:5000/todos/add
Content-Type: application/json

{
  "title": "New todo #1"
}

### Get todo count
DELETE http://localhost:5000/todos/delete/1
Accept: application/json

### Update a todo
POST http://localhost:5000/todos/update/1
Content-Type: application/json

{
  "title": "aaaaaaaaaaaa",
  "completed": true
}
